name: Release (PyPI Trusted Publishing + Environments)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      target:
        description: 'Publish target (manual runs only)'
        type: choice
        required: true
        options:
          - pypi
          - testpypi
        default: testpypi

permissions:
  contents: read
  id-token: write

concurrency:
  group: release-${{ github.ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build package (sdist + wheel)
        run: python -m build
      - name: Check distributions
        run: python -m twine check dist/* | cat
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    # From tags without hyphen (e.g., v1.2.3) OR manual dispatch with target=pypi
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !contains(github.ref_name, '-')) ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi')
    environment:
      name: pypi
      url: https://pypi.org/project/syntha/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish (OIDC Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          verbose: true

  publish-pypi-test:
    name: Publish to pypi-test
    needs: build
    runs-on: ubuntu-latest
    # From pre-release style tags (with '-') OR manual dispatch with target=pypi-test
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && contains(github.ref_name, '-')) ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi-test')
    environment:
      name: pypi-test
      url: https://test.pypi.org/project/syntha/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to pypi-test (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          verbose: true
          skip-existing: true